QLBanCay/Models/NuocSanXuat.cs
using System;
using System.Collections.Generic;

namespace QLBanCay.Models;

public partial class NuocSanXuat
{
    public string MaNuocSx { get; set; } = null!;

    public string TenNuocSx { get; set; } = null!;

    public virtual ICollection<DanhMucCay> DanhMucCays { get; set; } = new List<DanhMucCay>();
}

QLBanCay/Areas/Admin/Controllers/NuocSXController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLBanCay.Models;
using X.PagedList;

namespace QLBanCay.Areas.Admin.Controllers
{
    [Area("admin")]
    public class NuocSXController : Controller
    {
        QlbanCayContext csdl = new QlbanCayContext();
        public IActionResult Index()
        {
            return View();
        }

        [Route("NuocSanXuat")]
        public IActionResult NuocSanXuat(int? page)
        {
            //Số đối tượng hiển thị tối đa trên 1 trang
            int pageSize = 3;
            //Số trang hiện tại đang truy cập
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            //Khởi tạo 1 danh sách tự do
            var nsx = csdl.NuocSanXuats.AsNoTracking().OrderBy(x => x.MaNuocSx);
            PagedList<NuocSanXuat> paged_nsx = new PagedList<NuocSanXuat>(nsx, pageNumber, pageSize);
            //Khai báo 1 paged danh sách 
            return View(paged_nsx);
        }

        [Route("Themnuocsx")]
        [HttpGet]
        public IActionResult ThemNuocSX()
        {

            return View();
        }

        [Route("Themnuocsx")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ThemNuocSX(NuocSanXuat nsx)
        {
            if (ModelState.IsValid)
            {
                csdl.NuocSanXuats.Add(nsx);
                csdl.SaveChanges();
                return RedirectToAction("NuocSanXuat");
            }
            return View(nsx);
        }

        [Route("SuaNSX")]
        [HttpGet]
        public IActionResult SuaNSX(string mansx)
        {
            var NSX = csdl.NuocSanXuats.Find(mansx);
            return View(NSX);
        }

        [Route("SuaNSX")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SuaNSX(NuocSanXuat NSX)
        {
            if (ModelState.IsValid)
            {
                csdl.Update(NSX);
                /*csdl.Entry(sanpham).State = EntityState.Modified;*/
                csdl.SaveChanges();
                return RedirectToAction("NuocSanXuat");
            }
            return View(NSX);
        }

        [Route("XoaNSX")]
        [HttpGet]
        public IActionResult XoaNSX(string maNSX)
        {
            TempData["Message"] = "";
            csdl.Remove(csdl.NuocSanXuats.Find(maNSX));
            csdl.SaveChanges();
            TempData["Message"] = "Đã xoá nước sản xuất thành công";
            return RedirectToAction("NuocSanXuat");

        }
    }
}

QLBanCay/Areas/Admin/Views/NuocSX/NuocSanXuat.cshtml
@using QLBanCay.Models;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<NuocSanXuat>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "NuocSanXuat";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-body" style="min-height: 960px">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, Welcome Back!</h4>
                </div>
            </div>

            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Danh mục cây</a></li>
                    <li class="breadcrumb-item active"><a asp-area="admin" asp-controller="NuocSX" asp-action="NuocSanXuat">Nước sản xuất</a></li>
                </ol>
            </div>

            <!-- row -->
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Nước Sản Xuất</h4>
                            <a class="btn btn-primary float-right" asp-action="ThemNuocSX">Thêm mới</a>

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper">
                                    <p>@TempData["Message"]</p>
                                    <table class="table header-border" style="min-width: 500px;">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Mã nước
                                                </th>

                                                <th>
                                                    Tên nước
                                                </th>

                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.MaNuocSx)
                                                    </td>

                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.TenNuocSx)
                                                    </td>

                                                    <td>
                                                        <div class="dropdown">
                                                            <button type="button" class="btn btn-success light sharp" data-toggle="dropdown">
                                                                <svg width="20px" height="20px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg>
                                                            </button>
                                                            <div class="dropdown-menu">
                                                                <a class="dropdown-item" asp-action="SuaNSX" asp-route-mansx="@item.MaNuocSx">Edit</a>
                                                                <a class="dropdown-item" asp-action="XoaNSX" asp-route-mansx="@item.MaNuocSx">Delete</a>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    @Html.PagedListPager(Model, page=> Url.Action("NuocSanXuat", new {page=page}), new
                                    X.PagedList.Web.Common.PagedListRenderOptions(){
                                    LiElementClasses = new List<String> {"page-item"},
                                    PageClasses = new List<String> {"page-link"}
                                    })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLBanCay/Areas/Admin/Views/NuocSX/SuaNSX.cshtml
@model QLBanCay.Models.NuocSanXuat
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "SuaNSX";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-body" style="min-height: 960px">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, Welcome Back!</h4>
                </div>
            </div>

            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Danh mục cây</a></li>
                    <li class="breadcrumb-item active"><a asp-area="admin" asp-controller="NuocSX" asp-action="NuocSanXuat">Nước sản xuất</a></li>
                    <li class="breadcrumb-item active"><a asp-action="SuaNSX">Sửa nước sản xuất</a></li>
                </ol>
            </div>

            <!-- row -->
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Sửa nước sản xuất</h4>

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <form asp-action="SuaNSX">
                                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                                <input type="hidden" asp-for="MaNuocSx" />
                                                <div class="form-group">
                                                    <label asp-for="TenNuocSx" class="control-label"></label>
                                                    <input asp-for="TenNuocSx" class="form-control" />
                                                    <span asp-validation-for="TenNuocSx" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <input type="submit" value="Save" class="btn btn-primary" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    <div>
                                        <a asp-action="NuocSanXuat">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLBanCay/Areas/Admin/Views/NuocSX/ThemNuocSX.cshtml
@model QLBanCay.Models.NuocSanXuat
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "ThemNuocSX";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-body" style="min-height: 960px">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, Welcome Back!</h4>
                </div>
            </div>

            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Danh mục cây</a></li>
                    <li class="breadcrumb-item active"><a asp-area="admin" asp-controller="NuocSX" asp-action="NuocSanXuat">Nước sản xuất</a></li>
                    <li class="breadcrumb-item active"><a asp-action="ThemNuocSX">Thêm nước sản xuất mới</a></li>
                </ol>
            </div>

            <!-- row -->
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Thêm loại cây mới</h4>

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <form asp-action="ThemNuocSX">
                                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                                <div class="form-group">
                                                    <label asp-for="MaNuocSx" class="control-label"></label>
                                                    <input asp-for="MaNuocSx" class="form-control" />
                                                    <span asp-validation-for="MaNuocSx" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="TenNuocSx" class="control-label"></label>
                                                    <input asp-for="TenNuocSx" class="form-control" />
                                                    <span asp-validation-for="TenNuocSx" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <input type="submit" value="Create" class="btn btn-primary" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    <div>
                                        <a asp-action="NuocSanXuat">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>