QLBanCay/Areas/Admin/Controllers/DSNhanVienController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLBanCay.Models;
using X.PagedList;

namespace QLBanCay.Areas.Admin.Controllers
{
    [Area("admin")]
    public class DSNhanVienController : Controller
    {
        QlbanCayContext csdl = new QlbanCayContext();
        public IActionResult Index()
        {
            return View();
        }

        [Route("admin/DanhsachNV")]
        public IActionResult DanhsachNV(int? page)
        {
            //Số đối tượng hiển thị tối đa trên 1 trang
            int pageSize = 3;
            //Số trang hiện tại đang truy cập
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            //Khởi tạo 1 danh sách tự do
            var dsnv = csdl.NhanViens.AsNoTracking().OrderBy(x => x.TenNv);
            PagedList<NhanVien> paged_dsnv = new PagedList<NhanVien>(dsnv, pageNumber, pageSize);
            //Khai báo 1 paged danh sách 
            return View(paged_dsnv);
        }

        [Route("Themnhanvien")]
        [HttpGet]
        public IActionResult ThemNVMoi()
        {
            ViewBag.UserName = new SelectList(csdl.Users.ToList(), "UserName", "LoaiUser");
            return View();
        }

        [Route("Themnhanvien")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ThemNVMoi(NhanVien nhanvien)
        {
            if (ModelState.IsValid)
            {
                csdl.NhanViens.Add(nhanvien);
                csdl.SaveChanges();
                return RedirectToAction("DanhsachNV");
            }
            return View(nhanvien);
        }

        [Route("Suanhanvien")]
        [HttpGet]
        public IActionResult SuaNhanVien(string manv)
        {
            ViewBag.UserName = new SelectList(csdl.Users.ToList(), "UserName", "LoaiUser");
            var nv = csdl.NhanViens.Find(manv);
            return View(nv);
        }

        [Route("Suanhanvien")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SuaNhanVien(NhanVien nv)
        {
            if (ModelState.IsValid)
            {
                csdl.Update(nv);
                /*csdl.Entry(sanpham).State = EntityState.Modified;*/
                csdl.SaveChanges();
                return RedirectToAction("DanhsachNV");
            }
            return View(nv);
        }

        [Route("XoaNhanVien")]
        [HttpGet]
        public IActionResult XoaNhanVien(string maNV)
        {                 

            TempData["Message"] = "";
            var chiTietHD = csdl.HoaDonBans.Where(x => x.MaNv == maNV).ToList();
            if (chiTietHD.Count() > 0)
            {
                TempData["Message"] = "Không xoá được nhân viên này";
                return RedirectToAction("DanhsachNV");
            }
            csdl.Remove(csdl.NhanViens.Find(maNV));
            csdl.SaveChanges();
            TempData["Message"] = "Đã xoá nhân viên thành công";
            return RedirectToAction("DanhsachNV");

        }

    }
}

QLBanCay/Areas/Admin/Views/DSNhanVien/DanhsachNV.cshtml
@using QLBanCay.Models;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<NhanVien>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "DanhsachNV";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-body" style="min-height: 960px">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, Welcome Back!</h4>
                </div>
            </div>

            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Quản lý nhân viên</a></li>
                    <li class="breadcrumb-item active"><a asp-area="admin" asp-controller="DSNhanVien" asp-action="DanhsachNV">Danh sách nhân viên</a></li>
                </ol>
            </div>

            <!-- row -->
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Danh sách nhân viên</h4>
                            <a class="btn btn-primary float-right" asp-action="ThemNVmoi">Thêm mới</a>

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper">
                                    <p>@TempData["Message"]</p>
                                    <table class="display dataTable" style="min-width: 845px">
                                        <thead>
                                            <tr class="display text-center">
                                                <th>
                                                    Tên nhân viên
                                                </th>
                                                <th>
                                                    Địa chỉ
                                                </th>
                                                <th>
                                                    Vị trí
                                                </th>
                                                <th>
                                                    Số điện thoại
                                                </th>

                                                <th>
                                                    Ảnh
                                                </th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr class="display text-center">
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.TenNv)
                                                    </td>

                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.DiaChi)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.ViTri)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.SoDienThoai)
                                                    </td>

                                                    <td>
                                                        <img src="@Url.Content("../LayoutAdmin" + item.AnhDaiDien) " class="img-fluid rounded-circle" />

                                                    </td>

                                                    <td>
                                                        <div class="dropdown">
                                                            <button type="button" class="btn btn-success light sharp" data-toggle="dropdown">
                                                                <svg width="20px" height="20px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg>
                                                            </button>
                                                            <div class="dropdown-menu">
                                                                <a class="dropdown-item" asp-action="SuaNhanVien" asp-route-manv="@item.MaNv">Edit</a>
                                                                <a class="dropdown-item" asp-action="XoaNhanVien" asp-route-manv="@item.MaNv">Delete</a>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>

                                    @Html.PagedListPager(Model, page=> Url.Action("DanhsachNV", new {page=page}), new
                                    X.PagedList.Web.Common.PagedListRenderOptions(){
                                    LiElementClasses = new List<String> {"page-item"},
                                    PageClasses = new List<String> {"page-link"}
                                    })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLBanCay/Areas/Admin/Views/DSNhanVien/SuaNhanVien.cshtml
@model QLBanCay.Models.NhanVien
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "SuaNhanVien";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-body" style="min-height: 960px">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, Welcome Back!</h4>
                </div>
            </div>

            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Quản lý nhân viên</a></li>
                    <li class="breadcrumb-item active"><a asp-area="admin" asp-controller="DSNhanVien" asp-action="DanhsachNV">Danh sách nhân viên</a></li>
                    <li class="breadcrumb-item active"><a asp-action="SuaNhanVien">Sửa thông tin nhân viên</a></li>
                </ol>
            </div>

            <!-- row -->
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Sửa thông tin nhân viên</h4>

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <form asp-action="SuaNhanVien">
                                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                                <input type="hidden" asp-for="MaNv" />
                                                <div class="form-group">
                                                    <label asp-for="TenNv" class="control-label"></label>
                                                    <input asp-for="TenNv" class="form-control" />
                                                    <span asp-validation-for="TenNv" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="NgaySinh" class="control-label"></label>
                                                    <input asp-for="NgaySinh" class="form-control" />
                                                    <span asp-validation-for="NgaySinh" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="DiaChi" class="control-label"></label>
                                                    <input asp-for="DiaChi" class="form-control" />
                                                    <span asp-validation-for="DiaChi" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="SoDienThoai" class="control-label"></label>
                                                    <input asp-for="SoDienThoai" class="form-control" />
                                                    <span asp-validation-for="SoDienThoai" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="UserName" class="control-label"></label>
                                                    <select asp-for="UserName" class="form-control" asp-items="ViewBag.UserName"></select>
                                                    <span asp-validation-for="UserName" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="AnhDaiDien" class="control-label"></label>
                                                    <input asp-for="AnhDaiDien" class="form-control" />
                                                    <span asp-validation-for="AnhDaiDien" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="ViTri" class="control-label"></label>
                                                    <input asp-for="ViTri" class="form-control" />
                                                    <span asp-validation-for="ViTri" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <input type="submit" value="Save" class="btn btn-primary" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    <div>
                                        <a asp-action="DanhsachNV">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLBanCay/Areas/Admin/Views/DSNhanVien/ThemNVMoi.cshtml
@model QLBanCay.Models.NhanVien
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ThemNVMoi";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-body" style="min-height: 960px">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, Welcome Back!</h4>
                </div>
            </div>

            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Quản lý nhân viên</a></li>
                    <li class="breadcrumb-item active"><a asp-area="admin" asp-controller="DSNhanVien" asp-action="DanhsachNV">Danh sách nhân viên</a></li>
                    <li class="breadcrumb-item active"><a asp-action="ThemNVMoi">Thêm nhân viên</a></li>
                </ol>
            </div>

            <!-- row -->
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Thêm nhân viên mới</h4>

                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="example_wrapper" class="dataTables_wrapper">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <form method="post" asp-action="ThemNVMoi">
                                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                                <div class="form-group">
                                                    <label asp-for="MaNv" class="control-label"></label>
                                                    <input asp-for="MaNv" class="form-control" />
                                                    <span asp-validation-for="MaNv" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="TenNv" class="control-label"></label>
                                                    <input asp-for="TenNv" class="form-control" />
                                                    <span asp-validation-for="TenNv" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="NgaySinh" class="control-label"></label>
                                                    <input asp-for="NgaySinh" class="form-control" />
                                                    <span asp-validation-for="NgaySinh" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="DiaChi" class="control-label"></label>
                                                    <input asp-for="DiaChi" class="form-control" />
                                                    <span asp-validation-for="DiaChi" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="SoDienThoai" class="control-label"></label>
                                                    <input asp-for="SoDienThoai" class="form-control" />
                                                    <span asp-validation-for="SoDienThoai" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="UserName" class="control-label"></label>
                                                    <select asp-for="UserName" class="form-control" asp-items="ViewBag.UserName"></select>
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="AnhDaiDien" class="control-label"></label>
                                                    <input asp-for="AnhDaiDien" class="form-control" />                                                    
                                                    <span asp-validation-for="AnhDaiDien" class="text-danger"></span>                                                   
                                                </div>
                                                <div class="form-group">
                                                    <label asp-for="ViTri" class="control-label"></label>
                                                    <input asp-for="ViTri" class="form-control" />
                                                    <span asp-validation-for="ViTri" class="text-danger"></span>
                                                </div>
                                                <div class="form-group">
                                                    <input type="submit" value="Create" class="btn btn-primary" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    <div>
                                        <a asp-action="DanhsachNV">Back to List</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>